Problem definition
Predict EV adoption Share states as high or low Ev adoption

In [ ]:

import pandas as pd
Path = '/content/drive/MyDrive/Durgesh(testing)/Code (ML lifecycle)/EV_Data.csv'
Ev_adoption = pd.read_csv(Path)

In [ ]:
Ev_adoption

,Unnamed: 0.1,Unnamed: 0,ex party,year,EV Registrations,Total Vehicles,EV Share (%),Stations,Total Charging Outlets,Level 1,...,personal,reducetax,regulate,worried,price_cents_per_kwh,gasoline_price_per_gallon,Total,Trucks,Trucks_Share,Party
0,0,0,Alabama,2023,13000,4835900,0.27,424,1096,35,...,39.06,62.16,69.01,54.95,11.47,2.742,5446619.0,3.397137e+06,62.37,Republican
1,1,1,Alaska,2023,2700,559800,0.48,65,124,3,...,43.28,65.38,71.61,62.49,21.41,3.594,680974.0,5.175250e+05,76.00,Republican
2,2,2,Arizona,2023,89800,6529000,1.38,1198,3506,9,...,46.92,64.73,73.19,64.32,12.19,3.278,6447062.0,3.868118e+06,60.00,Democratic
3,3,3,Arkansas,2023,7100,2708300,0.26,334,833,3,...,39.08,63.39,68.58,56.21,9.73,2.760,3338322.0,2.291924e+06,68.65,Republican
4,4,4,California,2023,1256600,36850300,3.41,16381,49433,648,...,53.19,72.08,76.30,71.24,24.87,4.731,31057329.0,1.675788e+07,53.96,Democratic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,403,403,Virginia,2016,3100,7403200,0.04,427,991,174,...,NaN,NaN,NaN,NaN,9.09,NaN,NaN,NaN,NaN,NaN
404,404,404,Washington,2016,14900,6228400,0.24,738,1791,238,...,NaN,NaN,NaN,NaN,7.68,NaN,NaN,NaN,NaN,NaN
405,405,405,West Virginia,2016,100,1524400,0.01,43,96,5,...,NaN,NaN,NaN,NaN,8.98,NaN,NaN,NaN,NaN,NaN
406,406,406,Wisconsin,2016,2600,5368300,0.05,280,445,123,...,NaN,NaN,NaN,NaN,10.67,NaN,NaN,NaN,NaN,NaN
407,407,407,Wyoming,2016,100,615100,0.02,32,63,1,...,NaN,NaN,NaN,NaN,8.19,NaN,NaN,NaN,NaN,NaN

In [ ]:
Ev_adoption.dtypes

Unnamed: 0.1                               int64
Unnamed: 0                                 int64
state                                     object
year                                       int64
EV Registrations                           int64
Total Vehicles                             int64
EV Share (%)                             float64
Stations                                   int64
Total Charging Outlets                     int64
Level 1                                    int64
Level 2                                    int64
DC Fast                                    int64
fuel_economy                             float64
Incentives                               float64
Number of Metro Organizing Committees    float64
Population_20_64                         float64
Education_Bachelor                       float64
Labour_Force_Participation_Rate          float64
Unemployment_Rate                        float64
Bachelor_Attainment                      float64
Per_Cap_Income                           float64
affectweather                            float64
devharm                                  float64
discuss                                  float64
exp                                      float64
localofficials                           float64
personal                                 float64
reducetax                                float64
regulate                                 float64
worried                                  float64
price_cents_per_kwh                      float64
gasoline_price_per_gallon                float64
Total                                    float64
Trucks                                   float64
Trucks_Share                             float64
Party                                     object
dtype: object

In [ ]:
Ev_adoption.isnull()

,Unnamed: 0.1,Unnamed: 0,ex party,year,EV Registrations,Total Vehicles,EV Share (%),Stations,Total Charging Outlets,Level 1,...,personal,reducetax,regulate,worried,price_cents_per_kwh,gasoline_price_per_gallon,Total,Trucks,Trucks_Share,Party
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
404,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
405,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
406,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
407,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
Ev_adoption.isna().sum()

Unnamed: 0.1                               0
Unnamed: 0                                 0
ex party                                   0
year                                       0
EV Registrations                           0
Total Vehicles                             0
EV Share (%)                               0
Stations                                   0
Total Charging Outlets                     0
Level 1                                    0
Level 2                                    0
DC Fast                                    0
fuel_economy                             102
Incentives                                 8
Number of Metro Organizing Committees     51
Population_20_64                           0
Education_Bachelor                         0
Labour_Force_Participation_Rate            0
Unemployment_Rate                          0
Bachelor_Attainment                        0
Per_Cap_Income                             0
affectweather                            102
devharm                                  102
discuss                                  102
exp                                      102
localofficials                           102
personal                                 102
reducetax                                102
regulate                                 102
worried                                  102
price_cents_per_kwh                        0
gasoline_price_per_gallon                102
Total                                    108
Trucks                                   108
Trucks_Share                             108
Party                                    108
dtype: int64

In [ ]:
Ev_adoption.dropna()

,Unnamed: 0.1,Unnamed: 0,ex party,year,EV Registrations,Total Vehicles,EV Share (%),Stations,Total Charging Outlets,Level 1,...,personal,reducetax,regulate,worried,price_cents_per_kwh,gasoline_price_per_gallon,Total,Trucks,Trucks_Share,Party
0,0,0,Alabama,2023,13000,4835900,0.27,424,1096,35,...,39.06,62.16,69.01,54.95,11.47,2.742,5.446619e+06,3.397137e+06,62.37,Republican
1,1,1,Alaska,2023,2700,559800,0.48,65,124,3,...,43.28,65.38,71.61,62.49,21.41,3.594,6.809740e+05,5.175250e+05,76.00,Republican
2,2,2,Arizona,2023,89800,6529000,1.38,1198,3506,9,...,46.92,64.73,73.19,64.32,12.19,3.278,6.447062e+06,3.868118e+06,60.00,Democratic
3,3,3,Arkansas,2023,7100,2708300,0.26,334,833,3,...,39.08,63.39,68.58,56.21,9.73,2.760,3.338322e+06,2.291924e+06,68.65,Republican
4,4,4,California,2023,1256600,36850300,3.41,16381,49433,648,...,53.19,72.08,76.30,71.24,24.87,4.731,3.105733e+07,1.675788e+07,53.96,Democratic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,301,301,Virginia,2018,9900,7694500,0.13,615,1446,95,...,46.07,69.88,78.22,65.58,9.48,2.460,7.604646e+06,4.106265e+06,54.00,Democratic
302,302,302,Washington,2018,30200,6644500,0.45,961,2573,171,...,45.90,68.73,77.29,66.46,8.00,3.461,7.152413e+06,3.928127e+06,54.92,Democratic
303,303,303,West Virginia,2018,200,1515200,0.01,89,212,9,...,34.35,54.03,71.69,53.55,8.72,2.532,1.693719e+06,1.069746e+06,63.16,Republican
304,304,304,Wisconsin,2018,3700,5512200,0.07,306,557,90,...,39.91,67.22,78.50,60.46,10.58,2.407,5.683061e+06,3.244241e+06,57.09,Democratic
305,305,305,Wyoming,2018,200,623600,0.03,45,121,4,...,34.15,51.72,71.15,55.00,8.09,2.577,8.370241e+05,6.004518e+05,71.74,Republican

In [131]:
Ev_adoption.drop_duplicates()

,Unnamed: 0.1,Unnamed: 0,state,year,EV Registrations,Total Vehicles,EV Share (%),Stations,Total Charging Outlets,Level 1,...,personal,reducetax,regulate,worried,price_cents_per_kwh,gasoline_price_per_gallon,Total,Trucks,Trucks_Share,Party
0,0,0,Alabama,2023,13000,4835900,0.27,424,1096,35,...,39.06,62.16,69.01,54.95,11.47,2.742,5446619.0,3.397137e+06,62.37,Republican
1,1,1,Alaska,2023,2700,559800,0.48,65,124,3,...,43.28,65.38,71.61,62.49,21.41,3.594,680974.0,5.175250e+05,76.00,Republican
2,2,2,Arizona,2023,89800,6529000,1.38,1198,3506,9,...,46.92,64.73,73.19,64.32,12.19,3.278,6447062.0,3.868118e+06,60.00,Democratic
3,3,3,Arkansas,2023,7100,2708300,0.26,334,833,3,...,39.08,63.39,68.58,56.21,9.73,2.760,3338322.0,2.291924e+06,68.65,Republican
4,4,4,California,2023,1256600,36850300,3.41,16381,49433,648,...,53.19,72.08,76.30,71.24,24.87,4.731,31057329.0,1.675788e+07,53.96,Democratic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,403,403,Virginia,2016,3100,7403200,0.04,427,991,174,...,NaN,NaN,NaN,NaN,9.09,NaN,NaN,NaN,NaN,NaN
404,404,404,Washington,2016,14900,6228400,0.24,738,1791,238,...,NaN,NaN,NaN,NaN,7.68,NaN,NaN,NaN,NaN,NaN
405,405,405,West Virginia,2016,100,1524400,0.01,43,96,5,...,NaN,NaN,NaN,NaN,8.98,NaN,NaN,NaN,NaN,NaN
406,406,406,Wisconsin,2016,2600,5368300,0.05,280,445,123,...,NaN,NaN,NaN,NaN,10.67,NaN,NaN,NaN,NaN,NaN
407,407,407,Wyoming,2016,100,615100,0.02,32,63,1,...,NaN,NaN,NaN,NaN,8.19,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, state, year, EV Registrations, Total Vehicles, EV Share (%), Stations, Total Charging Outlets, Level 1, Level 2, DC Fast, fuel_economy, Incentives, Number of Metro Organizing Committees, Population_20_64, Education_Bachelor, Labour_Force_Participation_Rate, Unemployment_Rate, Bachelor_Attainment, Per_Cap_Income, affectweather, devharm, discuss, exp, localofficials, personal, reducetax, regulate, worried, price_cents_per_kwh, gasoline_price_per_gallon, Total, Trucks, Trucks_Share, Party]
Index: []

[0 rows x 36 columns]